artifact_uri: file:///Users/kushalkoshti/Work/InventoryDynamics/inventory-dynamics/mlruns/776245743342708479/2d1b42916f35487e83cec26e192fe2d1/artifacts
end_time: 1770212742869
entry_point_name: ''
experiment_id: '776245743342708479'
lifecycle_stage: active
run_id: 2d1b42916f35487e83cec26e192fe2d1
run_name: mysterious-smelt-852
source_name: ''
source_type: 4
source_version: ''
start_time: 1770212714673
status: 3
tags: []
user_id: kushalkoshti
