artifact_uri: file:///Users/kushalkoshti/Work/InventoryDynamics/inventory-dynamics/mlruns/776245743342708479/91cc14734917405c8fbeb36c5f7c7945/artifacts
end_time: 1770212637725
entry_point_name: ''
experiment_id: '776245743342708479'
lifecycle_stage: active
run_id: 91cc14734917405c8fbeb36c5f7c7945
run_name: unleashed-sponge-661
source_name: ''
source_type: 4
source_version: ''
start_time: 1770212609754
status: 3
tags: []
user_id: kushalkoshti
